# Generated by Django 2.2.12 on 2020-10-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
